Setup file
UWOrbital/CC1120Driver pull request #4
Opened 2022-04-07 08:51 UTC by amrits1

# Purpose
- Add abstractions to setup the registers needed for certain transmit and receive configuration 

# New Changes
- Created functions needed for setting symbol rate, modulation format, strobe commands, frequency, RX filter bandwidth, and other configuration settings

# Outstanding Changes
- Setup function that calls each of the new functions, with the correct parameters for our driver
- Any other setup functionality that should be abstracted out

2022-04-11 01:35 UTC, manumanuk requested changes
-TX side could still use a PA setup section
-Still need to merge in latest changes from main

2022-04-11 01:35 UTC, manumanuk commented on cc1120_arduino/cc1120_setup_transmit.c
> +void setGSFK()
Should return a boolean

2022-04-11 01:35 UTC, manumanuk commented on cc1120_arduino/cc1120_setup_recieve.c
> +bool setRXFilterBandwidth(int RXFilterBandwidth)
As per new [UW Orbital Style Guide](https://www.notion.so/uworbital/Software-Documentation-Style-Guide-f6526fd87fe04e949bc4150fe0a03a6c), we should rename these to snake_case

2022-04-11 01:35 UTC, manumanuk commented on cc1120_arduino/cc1120_setup_transmit.c
> +void setGSFK()
In the future, this function should include parameters for setting frequency deviation, manchester encoding, etc

2022-04-11 01:35 UTC, manumanuk commented on cc1120_arduino/cc1120_setup_transmit.c
> +bool setSymbolRate(int symbolRate)
Change any `int`s to `uint8_t`s to avoid ambiguity with size in memory

2022-04-11 01:35 UTC, manumanuk commented on cc1120_arduino/cc1120_setup_transmit.c
> +        return false;
We should avoid early returns

2022-04-11 01:35 UTC, manumanuk commented on cc1120_arduino/cc1120_setup_transmit.c
> +bool sendSRXStrobe()
We don't really need these strobe function wrappers - the strobe registers themselves are meant to be single register commands and super abstracted - we can just remove these and call cc1120_strobe_spi instead

Unless we want to maintain some sort of design philosophy where the users of our driver API never interact with the SPI functions directly

2022-04-11 01:35 UTC, manumanuk commented on cc1120_arduino/cc1120_setup_transmit.h
> +void setGSFK();
At minimum, we should include the function comments in the .h file as opposed to the .c, since that's where they are generally exposed to users.

2022-04-11 01:35 UTC, manumanuk commented on cc1120_arduino/cc1120_setup_transmit.c
> +    uint8_t data1 = STRATE_M << 4 || NtoKBits(STRATE_M, 16, 19);
Should explicitly set SRATE_E to 0 here

2022-04-11 01:35 UTC, manumanuk commented on cc1120_arduino/cc1120_setup_transmit.c
> +    int STRATE_E = 0;
Add a short comment explaining SRATE_E=0

2022-04-11 01:35 UTC, manumanuk commented on cc1120_arduino/cc1120_setup_transmit.c
> +    long int STRATE_M = (pow(2, 38) * ((double)symbolRate / 1000)) / FXOSC;
Should we get FXOSC from a cc1120_read_spi just to be safe, as opposed to using a constant?

2022-04-11 01:35 UTC, manumanuk commented on cc1120_arduino/cc1120_utility.h
> +int NtoKBits(int number, int start, int end);
Change naming to snake_case

2022-04-11 01:35 UTC, manumanuk commented on cc1120_arduino/cc1120_setup_transmit.c
> +}
We should merge this operation into the frequency configuration function

2022-04-11 01:35 UTC, manumanuk commented on cc1120_arduino/cc1120_setup_transmit.c
> + * @param frequency - The frequency to set to.
Clarify that this is the VCO frequency and not the RF frequency

2022-04-11 01:35 UTC, manumanuk commented on cc1120_arduino/cc1120_setup_transmit.c
> + * @param frequency - The frequency to set to.
Alternatively take in RF frequency as a parameter and grab the LO Divider value with a SPI read. (Though I think it would be better not to do that because it adds unnecessary operations)

Side note: I really wish we were using OOP so we could keep this private and therefore prevent people who don't know understand the nuances from using the function

2022-04-11 01:35 UTC, manumanuk commented on cc1120_arduino/cc1120_utility.c
> + * @brief Gets the nth to kth bits of an unsigned integer.
Maybe include a short comment on whether or not the bounds here are inclusive.

2022-04-11 01:35 UTC, manumanuk commented on cc1120_arduino/cc1120_setup_recieve.c
> +}
Add a newline at the end of the file

2022-04-16 00:38 UTC, amrits1 commented on cc1120_arduino/cc1120_setup_transmit.c
> + * @param frequency - The frequency to set to.
I added this (first option), but isn't this already shown in the function name? Unless I'm misinterpreting where you want me to clarify it

2022-04-16 00:39 UTC, amrits1 commented on cc1120_arduino/cc1120_setup_recieve.c
> +}
Added

2022-04-16 00:39 UTC, amrits1 commented on cc1120_arduino/cc1120_utility.c
> + * @brief Gets the nth to kth bits of an unsigned integer.
Added

2022-04-16 00:41 UTC, amrits1 commented on cc1120_arduino/cc1120_setup_transmit.c
> +}
Which function? set_gfsk?

2022-04-16 05:55 UTC, amrits1 commented on cc1120_arduino/cc1120_setup_transmit.c
> +    long int STRATE_M = (pow(2, 38) * ((double)symbolRate / 1000)) / FXOSC;
Correct me if I'm wrong, but my understanding was that FXOSC is a constant for the chip and isn't controlled by any of the registers

2022-04-16 05:55 UTC, amrits1 commented on cc1120_arduino/cc1120_setup_transmit.c
> +    int STRATE_E = 0;
Added

2022-04-16 05:55 UTC, amrits1 commented on cc1120_arduino/cc1120_setup_transmit.c
> +    uint8_t data1 = STRATE_M << 4 || NtoKBits(STRATE_M, 16, 19);
Changed, that line was supposed to be `uint8_t data1 = STRATE_E << 4 || NtoKBits(STRATE_M, 16, 19);`

2022-04-16 21:35 UTC, manumanuk commented on cc1120_arduino/cc1120_setup_transmit.c
> +    long int STRATE_M = (pow(2, 38) * ((double)symbolRate / 1000)) / FXOSC;
There seems to be an XOSC register in the extended address space but I checked the register definition and I think you're right, there's no control over the frequency

2022-04-16 21:37 UTC, manumanuk commented on cc1120_arduino/cc1120_setup_transmit.c
> +    uint8_t data1 = STRATE_M << 4 || NtoKBits(STRATE_M, 16, 19);
You accidentally wrote `STRATE_M << 4`

2022-04-16 21:38 UTC, manumanuk commented on cc1120_arduino/cc1120_setup_transmit.c
> + * @param frequency - The frequency to set to.
I was talking specifically about the parameter

2022-04-16 21:39 UTC, manumanuk commented on cc1120_arduino/cc1120_setup_transmit.c
> + * @param frequency - The frequency to set to.
Though I also really think we should merge this function into setRFFrequency, I don't see a need to call setVCOFrequency standalone

2022-04-16 22:37 UTC, amrits1 commented on cc1120_arduino/cc1120_setup_transmit.c
> +    uint8_t data1 = STRATE_M << 4 || NtoKBits(STRATE_M, 16, 19);
Yep I changed it, I think you're looking at the old version

2022-07-16 19:59 UTC, closed without merging